# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://janhendrikewers.uk/
title: Jan-Hendrik Ewers
author: Jan-Hendrik Ewers
description: Personal blog and resume
avatar: profile.png
email: jh.ewers@gmail.com
github: iwishiwasanealge # username
twitter: jhewers
linkedin: jh-ewers

exclude: [vendor]
