# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://janhendrikewers.uk/
title: Jan-Hendrik Ewers
author: Jan-Hendrik Ewers
description: Personal blog and resume for Jan-Hendrik Ewers.
avatar: profile.png
email: jh.ewers@gmail.com
github: iwishiwasaneagle # username
twitter: jhewers
linkedin: jh-ewers
google_analytics: G-D63RVP8Q8M

exclude: [vendor,utils]
