# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
include:
  - _pages
plugins: ["jekyll/scholar"]
rdiscount:
  extensions: [smart]
permalink: /:title
port: 3000

# edit here to achieve your personal greatness
url: https://janhendrikewers.uk
title: Jan-Hendrik Ewers
author: Jan-Hendrik Ewers
description: Personal blog and resume for Jan-Hendrik Ewers.
avatar: profile.png
email: j.ewers.1@research.gla.ac.uk
github: iwishiwasaneagle
twitter: jhewers
linkedin: jh-ewers
orcid: 0000-0002-8498-1410
utterances: iwishiwasaneagle/janhendrikewers.uk

plausible_url: https://divine-wood-7bde.dev-jh-ewers4177.workers.dev
plausible_script: 18dcc14a8dd9f785.js
plausible_event: bd7483245a4d6b07

bmac_url: https://www.buymeacoffee.com/janhendrikewers.uk


# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:

exclude:
  - vendor
  - utils
