# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
include:
 - _pages
rdiscount:
  extensions: [smart]
permalink: /:title.html
port: 3000

# edit here to achieve your personal greatness
url: https://janhendrikewers.uk
title: Jan-Hendrik Ewers
author: Jan-Hendrik Ewers
description: Personal blog and resume for Jan-Hendrik Ewers.
avatar: profile.png
email: j.ewers.1@research.gla.ac.uk 
github: iwishiwasaneagle
twitter: jhewers
linkedin: jh-ewers
google_ads: 4960626434138868
orcid: 0000-0002-8498-1410
utterances: iwishiwasaneagle/janhendrikewers.uk

algolia:
  application_id: '2PA5ICUOKI'
  index_name: 'personal_website'
  public_key: '0959bf81c3e205f75ceb34c1fd0b378a'
  files_to_exclude: ['blog.html', 'atom.html', 'index.html', '404.html']
  settings:                                                                      
    searchableAttributes:                                                        
      - title                                                                    
      - headings                                                                 
      - unordered(content)                                                       
      - unordered(tags)                                                          
      - unordered(url)  

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:


exclude: 
  - vendor
  - utils
