name: CD
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          
      - name: Build website
        run: JEKYLL_ENV=production bundle exec jekyll build --lsi
          
      - name: Create .nojekyll file
        run: touch _site/.nojekyll

      - name: Upload the docs
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: _site/
          clean-exclude: |
            .nojekyll
            CNAME

      - name: Auto-index website
        run: ALGOLIA_API_KEY=${{ secrets.ALGOLIA_ADMIN_KEY }} bundle exec jekyll algolia
      
      - name: Tell google to reindex
        run: curl "https://www.google.com/ping?sitemap=https://${{ secrets.WWW_DIR }}/sitemap.xml"
