name: CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Integrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true
          
      - name: Build website
        run: JEKYLL_ENV=production bundle exec jekyll build --lsi
