name: Build and deploy to server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
          
      - name: Build website
        run: JEKYLL_ENV=production bundle exec jekyll build
          
      - name: "Set up SSH agent"
        uses: webfactory/ssh-agent@v0.5.3
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
          
      - name: "Add GitHub to the SSH known hosts file"
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        
      - name: Upload to server
        run: rsync -avr --rsh "ssh" --exclude 'utils/**' --exclude={'utils/**'} --delete-after --delete-excluded _site/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WWW_DIR }}
      
      - name: Ensure correct permissions
        run: | 
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "find ${{ secrets.WWW_DIR }} -type d -exec chmod 755 {} \;"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "find ${{ secrets.WWW_DIR }} -type f -exec chmod 644 {} \;"
