name: Build and deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses:  helaili/jekyll-action@v2
        with:
          build_only: true
          
      - name: Upload to DO
        run: | 
          eval $(ssh-agent -s)
          echo "$SSH_KEY" | tr -d '\r' | ssh-add -
          rsync -avr --rsh "ssh" --exclude 'utils/**' --delete-after --delete-excluded _site/ www@138.68.159.66:/var/www/janhendrikewers.uk/html
